### ISSUE TITLE
Update information on homepage about meeting times and locations

### ISSUE THREAD

**Issue by chris-tse** [FreeCodeCampOKC/fccokc_web#14]
The information on our homepage regarding meeting times is no longer accurate. It should reflect that we stream virtual meetups the 2nd Sunday of each month along with other occasional in-person meetups organized on the fly. 

The meeting information code can be found here:
https://github.com/FreeCodeCampOKC/fccokc_web/blob/main/site/index.html#L16

**Comment by samuelshoun** [comment]
Currently working this.
