### ISSUE TITLE
Add link to our Discord server to the contact page

### ISSUE THREAD

**Issue by chris-tse** [FreeCodeCampOKC/fccokc_web#18]
We would like a link added to our `/contact` page to our Discord server at https://fccokc.com/discord for anyone who might be interested in it.

The spot to add this new link would be located here between the Slack and Calendly link:
https://github.com/FreeCodeCampOKC/fccokc_web/blob/main/site/contact.html#L18

It should be formatted something like
Discord: [freeCodeCamp Oklahoma Discord](https://fccokc.com/discord)

**Comment by himanshu007-creator** [comment]
Hi i would like to work on this issue

**Comment by chris-tse** [comment]
@himanshu007-creator Thanks for expressing interest! I'd like to give some time to see if any local members of our group would like to tackle this first.
