### ISSUE TITLE
Add a new link to resources page

### ISSUE THREAD

**Issue by chris-tse** [FreeCodeCampOKC/fccokc_web#9]
Let's add this link to our resources page, submitted to us via email: https://couponfollow.com/research/learn-to-code-from-home

**Comment by AyeshaTayyab** [comment]
i am interested in resolving this issue.

**Comment by kacollins** [comment]
Please do, @AyeshaTayyab!

**Comment by AyeshaTayyab** [comment]
I have created a pull request.
